services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: partyyy
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db/:/data/db/
    network_mode: "host"
  party:
    build: .
    ports:
      - "8000:5000"
